version: "3"

volumes:
  postgres-data:
    external: true

services:
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: aetra
      POSTGRES_DB: aetra
  server:
    image: my-node-app
    build:
      context: ./server
    ports:
      - 8010:8000
    volumes:
      - ./server:/app
    environment:
      DATABASE_URL: postgresql://server:password123@db/server
      WAIT_HOSTS: db:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
  my-aetra-app:
    build:
      context: ./my-aetra-app
    working_dir: /app
    volumes:
      - ./my-aetra-app:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_AETRA_API_HOST: http://localhost:8010
