###
GET http://localhost:8010/users

###
POST http://localhost:8010/users
Content-Type: application/json

{
    "name": "james",
    "email": "james@email.com"
}

###
DELETE http://localhost:8010/users/2

###
GET http://localhost:8010/users/1

###
PUT http://localhost:8010/users/1
Content-Type: application/json

{
    "name": "jamie2",
    "email": "jamie@email.com"
}


###
GET http://localhost:8010/products

###
POST http://localhost:8010/products
Content-Type: application/json

{
    "name": "Green Loose Leaf Tea",
    "description": "Sourced from LamDong, VN",
    "price": 50,
    "size": 15
}

###
DELETE http://localhost:8010/products/1

###
GET http://localhost:8010/products/1

###
PUT http://localhost:8010/products/1
Content-Type: application/json

{
    "name": "Black Assam Tea",
    "description": "Sourced from LamDong, VN",
    "price": 30,
    "size": 10
}
