###
GET http://localhost:8010/users

###
GET http://localhost:8010/users/logout

###
GET http://localhost:8010/users/protected

###
POST http://localhost:8010/users/register
Content-Type: application/json

{
    "name": "hi",
    "email": "hello@email.com",
    "password": "123"
}

###
POST http://localhost:8010/users/login
Content-Type: application/json

{
    "email": "hello@email.com",
    "password": "123"
}

###
GET http://localhost:8010/products

###
POST http://localhost:8010/products
Content-Type: application/json

{
    "name": "Assam Black Tea",
    "description": "Sourced from LamDong, VN",
    "price": 45,
    "weight": 20,
    "image_url": "",
    "stock_quantity": 20
}

###
DELETE http://localhost:8010/products/4

###
GET http://localhost:8010/products/3

###
PUT http://localhost:8010/products/1
Content-Type: application/json

{
    "name": "Earl Grey Tea",
    "description": "Sourced from LamDong, VN",
    "price": 25,
    "weight": 15,
    "image_url": "",
    "stock_quantity": 50
}

###
GET http://localhost:8010/carts

###
GET http://localhost:8010/carts/all

###
POST http://localhost:8010/carts/add
Content-Type: application/json

{
    "product_id": 1,
    "quantity": 1
}

###
PUT http://localhost:8010/carts/remove
Content-Type: application/json

{
    "product_id": 3
}

###
PUT http://localhost:8010/carts/decrease
Content-Type: application/json

{
    "product_id": 2
}

###
DELETE http://localhost:8010/carts

###
POST http://localhost:8010/carts/checkout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJoZWxsb0BlbWFpbC5jb20iLCJpYXQiOjE2OTkyNTQ0MDEsImV4cCI6MTY5OTI1ODAwMX0.tpUKu6FoxjiThD1XPHuv785Ypq2g7GWvTjacC4z4J5g

{}

###
GET http://localhost:8010/orders/

###
GET http://localhost:8010/orders/all
