###
GET http://localhost:8010/users

###
GET http://localhost:8010/users/logout

###
GET http://localhost:8010/users/protected

###
POST http://localhost:8010/users/register
Content-Type: application/json

{
    "name": "hi",
    "email": "hello@email.com",
    "password": "123"
}

###
POST http://localhost:8010/users/login
Content-Type: application/json

{
    "email": "t@e.com",
    "password": "123456"
}

###
POST http://localhost:8010/users
Content-Type: application/json

{
    "name": "guava5",
    "email": "hi@email.com"
}

###
DELETE http://localhost:8010/users/2

###
GET http://localhost:8010/users/1

###
PUT http://localhost:8010/users/1
Content-Type: application/json

{
    "name": "jamie2",
    "email": "jamie@email.com"
}


###
GET http://localhost:8010/products

###
POST http://localhost:8010/products
Content-Type: application/json

{
    "name": "Oolong Tea",
    "description": "Sourced from LamDong, VN",
    "price": 50,
    "weight": 15,
    "image_url": "",
    "stock_quantity": 0
}

###
DELETE http://localhost:8010/products/2

###
GET http://localhost:8010/products/1

###
PUT http://localhost:8010/products/1
Content-Type: application/json

{
    "name": "Earl Grey Tea",
    "description": "Sourced from LamDong, VN",
    "price": 30,
    "weight": 15,
    "image_url": "",
    "stock_quantity": 0
}

###
GET http://localhost:8010/carts

###
GET http://localhost:8010/carts/all

###
POST http://localhost:8010/carts/add
Content-Type: application/json

{
    "product_id": 5,
    "quantity": 1
}

###
PUT http://localhost:8010/carts/decrease
Content-Type: application/json

{
    "product_id": 3
}

###
DELETE http://localhost:8010/carts
